arb-dir:  shareds/shared_libraries/lib/l10n
template-arb-file: app_id.arb
output-localization-file: /Users/bijantyum/Project/flutter/flutter_story_dicoding_intermediate/shareds/shared_libraries/lib/intl/app_localizations.dart